from django.conf.urls.defaults import patterns, url
from mrwf.extra import views

urlpatterns = patterns('mrwf.extra.views.abook',
 url(r'^$', views.abook.SearchView.as_view(), name='search'),
 url(r'^browse/new/$', views.abook.BrowseNewView.as_view(), name='browse_new'),
 url(r'^add/person/$',
     views.abook.PersonAddView.as_view(), name='add_person'),
 url(r'^person/(?P<obj_id>\d+)/$',
     views.abook.PersonView.as_view(), name='person'),
 url(r'^person/(?P<obj_id>\d+)/edit/$',
     views.abook.PersonEditView.as_view(), name='edit_person'),
 url(r'^person/(?P<obj_id>\d+)/activate/$',
     views.abook.PersonActivateView.as_view(), name='activate_person'),
 url(r'^person/(?P<obj_id>\d+)/disable/$',
     views.abook.PersonDisableView.as_view(), name='disable_person'),
 url(r'^person/(?P<obj_id>\d+)/delete/$',
     views.abook.PersonDeleteView.as_view(), name='delete_person'),
 url(r'^person/(?P<obj_id>\d+)/choose_member/$',
     views.abook.PersonChooseMemberView.as_view(), name='add_member_person'),
 url(r'^person/(?P<obj_id>\d+)/save_member/$',
     views.abook.PersonSaveMemberView.as_view(), name='save_member_person'),
 url(r'^add/org/$',
     views.abook.OrgAddView.as_view(), name='add_organisation'),
 url(r'^org/(?P<obj_id>\d+)/$',
     views.abook.OrgView.as_view(), name='organisation'),
 url(r'^org/(?P<obj_id>\d+)/edit/$',
     views.abook.OrgEditView.as_view(), name='edit_organisation'),
 url(r'^org/(?P<obj_id>\d+)/activate/$',
     views.abook.OrgActivateView.as_view(), name='activate_organisation'),
 url(r'^org/(?P<obj_id>\d+)/disable/$',
     views.abook.OrgDisableView.as_view(), name='disable_organisation'),
 url(r'^org/(?P<obj_id>\d+)/delete/$',
     views.abook.OrgDeleteView.as_view(), name='delete_organisation'),
 url(r'^org/(?P<obj_id>\d+)/choose_member/$',
     views.abook.OrgChooseMemberView.as_view(),name='add_member_organisation'),
 url(r'^org/(?P<obj_id>\d+)/save_member/$',
     views.abook.OrgSaveMemberView.as_view(),name='save_member_organisation'),
 url(r'^member/(?P<obj_id>\d+)/edit/$',
     views.abook.MemberEditView.as_view(), name="edit_member"),
)
